name: Build LaTeX PDF

on:
  push:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Generate changelist number
      - name: Get changelist number
        id: changelist
        run: echo "CHANGE_ID=$(git rev-list --count HEAD)" >> $GITHUB_ENV

      # Step 3: Inject version number into LaTeX file
      - name: Add version number
        run: |
          sed -i "s/\\newcommand{\\version}{.*}/\\newcommand{\\version}{${{ env.CHANGE_ID }}}/" itManual.tex

      # Step 4: Compile LaTeX 
      - name: Set up LaTeX
        uses: xu-cheng/latex-action@v3
        with:
          root_file: itManual.tex

      # Step 5: Save or upload the PDF
      - name: Upload PDF artifact
        uses: actions/upload-artifact@v4
        with:
          name: DevOpsConfigurationSTM-pdf
          path: itManual.pdf
